Tildes y typos arreglados en el post
esanchez2898/hyperblog pull request #1
Opened 2021-05-25 22:11 UTC by esanchez2898

No debimos pasar este error a Master

2021-05-25 22:17 UTC, armando2898 requested changes
En vez de usar tildes usen entidades HTML

2021-05-25 22:24 UTC, esanchez2898 commented
Cambios hechos, por favor hazme el merge

2021-05-25 22:26 UTC, armando2898 approved these changes
Excelente, eso era!

2021-05-25 22:28 UTC, merged

2021-06-17 21:30 UTC, esanchez2898 commented on blocpost.html
> +            <p>Y este es el p&aacute;rrafo de inicio donde vamos a explicar las cosas incre&iacute;bles que se pueden hacer con ramas</p>
Comentario no 1